### ISSUE TITLE
Stream lost/cracky after a while

### ISSUE THREAD

**Issue by njordan77** [schreibfaul1/ESP32-vs1053_ext#1]
Hi,
is there anything i can do so that my streams are not getting lost completely/cracky after a while (hours).
Sometimes it still works even when i had the system running over several hours...but its not like the system is a 24/7 approach.

Using ESP32 Matrix Core, and a 128kbit Austrian Ö3 stream.

Any tuning i could try. Is there any parameter to set buffer length? have seen something in different adafruit library but not sure how to get this working.

Cheers,
Norbert

**Comment by schreibfaul1** [comment]
Hi njordan77,
the stream is likely to break and the buffer will get empty. This happens to me extremely seldom and can be triggered from outside. It is certainly possible to rebuild the connection in case of a broken stream. I'm going to watch this in a long-term test and find a solution.  
sf1

**Comment by schreibfaul1** [comment]
If the stream is lost, the connection will be restarted after a few seconds, I hope this works well.
