### ISSUE TITLE
Unable to switch from SD > Web > SD

### ISSUE THREAD

**Issue by B4stl3r** [schreibfaul1/ESP32-vs1053_ext#10]
Hi (oder auch servus),

I like the library very much, but if it want to switch (lets assume a button event) between sources, this wont work...

I start with a .mp3 from SD in setup():
`player.connecttoSD("filename.mp3");`

due to a button press, i switch to:
```
player.begin();
player.connecttohost("http://thiscouldbeastreamurl.fm/");
```

and with another button press i want to switch again to SD:
```
player.begin();
delay(10);
player.connecttoSD("anotherfilename.mp3");
```

There's no more audio output anymore when switching back to SD..

If i then switch back to Webstream I'm running into this line (885ff):
`if(vs1053_info) vs1053_info("Stream lost -> try new connection");`

any ideas?

Thanks in advance!

**Comment by clear-sky** [comment]
please use WiFi.disconnect(); before player.connecttoSD("filename.mp3");

**Comment by B4stl3r** [comment]
I've reorganized my code and also changed the library a bit, now its working as in the example's.
