### ISSUE TITLE
URL that needs login and password - How to

### ISSUE THREAD

**Issue by bergvdna** [schreibfaul1/ESP32-vs1053_ext#6]
Fantastic project. Thanks.
But i neew to open a stream with login en password.

In WinAmp this work url/loginname/password
Then it opens a window to edit/fill in the login:password (that format).

How can i tackle this problem?

Thanks ahead.
a.vdberg@hccnet.nl

**Comment by schreibfaul1** [comment]
Data streams from radio stations do not need access data, which url is it?

**Comment by bergvdna** [comment]
Translate by Google from Dutch version

Dear Wolle (?),

Thanks for the super-fast response.

It is a sick old woman who through her tablet (and Firefox) until recently
could use a kind of church phone.

But she can not (see) that anymore and it becomes too difficult.

So she must have a simple box with an on and off button and a volume
control.

So your project is exactly what I am looking for!

Unfortunately, the server (from KzWeb) apparently makes a request to
confirm login and password when signing up.

Usually <ENTER> is sufficient to continue.
Sometimes it has to be twice.

I do not know how I can realize / test this with the MiniWebRadio.

Another difficulty is that only certain times are broadcast during the week.

But maybe you can help me on my way to solve this problem.

I have added some documentation links and JPG file about connentioninfo
WinAmp..

http://www.kzweb.nl/docs/index.php?id=radio-config
http://www.kzweb.nl/docs/index.php?id=radio-config&fullmanual=yes&version=manual-070307


Thank you very much.
Arie van den Berg.

NB.

There appears to be a web radio for sale that functions, but that needs
many buttons and also a WiFi dongle.
So this would not be my choice.


---------------------------------------------------------
Dutch version
Beste Wolle(?),

Bedankt voor de supersnelle reactie.

Het gaat om een zieke oude vrouw die via haar tablet (en Firefox) tot voor
kort gebruik kon maken van een soort kerktelefoon.

Maar dat kan zij niet meer (zien) en het wordt te moeilijk.

Dus zij moet een simple kastje hebben met een aan- en uitknop en een
volumeregelaar.

Dus Uw projekt is precies wat ik zoek!

Helaas doet de server (van KzWeb) bij het aanmelden kennelijk een verzoek
om login en wachtwoord te bevestigen.

Meestal is één keer <ENTER> voldoende om verder te gaan.
Soms moet het twee keer.

Ik weet niet hoe ik dat kan realiseren / testen met de MiniWebRadio.

Nog een moeilijkheid is dat er alleen bepaalde tijden in de week wordt
uitgezonden.

Maar misschien kunt u mij wat op weg helpen om dit probleem op te lossen.

Ik heb wat documentatie (links) toegevoegd en een JPG bestand met connectie
info van WinAmp .
http://www.kzweb.nl/docs/index.php?id=radio-config
http://www.kzweb.nl/docs/index.php?id=radio-config&fullmanual=yes&version=manual-070307

Vast hartelijk bedankt.
Arie van den Berg.

NB.

Er blijkt een webradio te koop te zijn die funtioneeert maar die heeft veel
knoppen en ook nog eens een WiFi-dongel nodig.
Dus dit zou niet mijn keuze zijn.
--------------------------------------------------------------------------------------------------------------------------------------

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op do 31 jan. 2019 om 23:14 schreef Wolle <notifications@github.com>:

**Comment by bergvdna** [comment]
Dear Wolle,

I found some additional information about KzWeb.
It is in Dutch, but the last sentence is very important.

It says:
"To listen to this signal any PC program can be used that supports
streaming MP3 files via HTTP, the only extra requirement is that this
software must also support HTTP authentication."

Hope this helps.

Best regards,
Arie



Techniek

KZweb maakt gebruik van "open source sofware". Hierdoor zijn er geen
licentie kosten aan verbonden. Ook de speciaal ontwikkelde software is vrij
van licentie kosten. Wel zijn er voorwaarden voor het gebruik van de
gebruikte software.

De gekozen techniek is dezelfde die al gedurende jaren door internet
radio's wordt gebruikt. Hiermee is de stabiliteit bewezen. Tevens biedt
deze software de mogelijkheid om de uitzending uitsluitend aan
geautorisieerde luisteraars aan te bieden en maakt hiermee publieke toegang
onmogelijk.

De server ontvangt het geluidssignaal rechtstreeks van de
geluidsinstallatie. Vervolgens wordt dit signaal door de software "live"
omgezet in het MP3 formaat ("encoding"). Deze wordt doorgegeven aan de
distributiesoftware ("streaming server"). Deze bepaalt welke luisteraar het
MP3 signaal mag ontvangen. Indien de gebruiker geautoriseerd is, ontvangt
de luisteraar het streaming MP3 signaal middels het HTTP protocol. Om dit
signaal te beluisteren kan ieder PC programma gebruikt worden die streaming
MP3 bestanden middels HTTP ondersteunt. Het enige extra vereiste hierbij is
dat deze software ook HTTP authenticatie moet ondersteunen.

Op do 31 jan. 2019 om 23:14 schreef Wolle <notifications@github.com>:

**Comment by SurenBono** [comment]
check a stable version of esp8266 ...webradio fix https://github.com/SurenBono/Alternate_Edzelf_Esp8266_WebRadio_

**Comment by bergvdna** [comment]
URL that needs login and password - How to
#6 opened on 31 Jan 2019 by bergvdna


Issue may be closed. 
Ed Smallenburg gave me the solution. 
See below the modification in the <ConnectToHost> function. 
In Auth the credentials must be placed as user:password. 
It works great this way.




>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
String Auth="user:passwd"
.........................
In ConnectToHost
.........................
String authBase64="";
.........................
.........................


if ( Auth != "" )                               // Should be user:passwd
    { 
       authBase64=Auth; // keep original
       authBase64 = base64::encode ( Auth.c_str() ) ;     // Encode
       authBase64 = String ( "Authorization: Basic " ) +
              authBase64 + String ( "\r\n" ) ;
    }
    String resp=String("GET ") + extension +
                String(" HTTP/1.1\r\n") +
                String("Host: ") + hostwoext +
                String("\r\n") +
                String("Icy-MetaData:1\r\n") +
                authBase64 +
                String("Connection: close\r\n\r\n");
    sprintf(sbuf, "resp string is %s", resp.c_str());
